"""Initial schema

Revision ID: 4abdfcb7d7a9
Revises: 
Create Date: 2026-08-18 20:27:20.520080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abdfcb7d7a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_repository'), ['repository'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_organization_id'), ['organization_id'], unique=False)

    op.create_table('environments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_environments_project_id'), ['project_id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('exception_type', sa.String(length=255), nullable=False),
    sa.Column('exception_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('team_id', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('project_policies',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('auto_merge_threshold', sa.Float(), nullable=False),
    sa.Column('mandatory_review_threshold', sa.Float(), nullable=False),
    sa.Column('restricted_files', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_policies_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_policies_project_id'), ['project_id'], unique=False)

    op.create_table('repositories',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_repositories_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repositories_project_id'), ['project_id'], unique=False)

    op.create_table('fault_locations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('incident_id', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fault_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fault_locations_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fault_locations_organization_id'), ['organization_id'], unique=False)

    op.create_table('incident_events',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('incident_id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_events_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('patch_candidates',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('incident_id', sa.String(length=50), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patch_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patch_candidates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_patch_candidates_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patch_candidates_organization_id'), ['organization_id'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('patch_candidate_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patch_candidate_id'], ['patch_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_decided_by'), ['decided_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_patch_candidate_id'), ['patch_candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_status'), ['status'], unique=False)

    op.create_table('pull_requests',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('patch_candidate_id', sa.String(length=50), nullable=False),
    sa.Column('github_pr_number', sa.Integer(), nullable=False),
    sa.Column('github_pr_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patch_candidate_id'], ['patch_candidates.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pull_requests_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pull_requests_patch_candidate_id'), ['patch_candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pull_requests_project_id'), ['project_id'], unique=False)

    op.create_table('sandbox_jobs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('patch_candidate_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patch_candidate_id'], ['patch_candidates.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sandbox_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sandbox_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sandbox_jobs_patch_candidate_id'), ['patch_candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sandbox_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sandbox_jobs_status'), ['status'], unique=False)

    op.create_table('trust_evaluations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('patch_candidate_id', sa.String(length=50), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('mutation_score', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patch_candidate_id'], ['patch_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trust_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trust_evaluations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_evaluations_patch_candidate_id'), ['patch_candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_evaluations_trust_score'), ['trust_score'], unique=False)

    op.create_table('ci_statuses',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('pull_request_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('context', sa.String(length=255), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ci_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ci_statuses_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ci_statuses_pull_request_id'), ['pull_request_id'], unique=False)

    op.create_table('mutations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('trust_evaluation_id', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('original_operator', sa.String(length=100), nullable=False),
    sa.Column('mutated_operator', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['trust_evaluation_id'], ['trust_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mutations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mutations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mutations_trust_evaluation_id'), ['trust_evaluation_id'], unique=False)

    op.create_table('sandbox_executions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('sandbox_job_id', sa.String(length=50), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sandbox_job_id'], ['sandbox_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sandbox_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sandbox_executions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sandbox_executions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sandbox_executions_sandbox_job_id'), ['sandbox_job_id'], unique=False)

    op.create_table('test_runs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('sandbox_execution_id', sa.String(length=50), nullable=True),
    sa.Column('test_suite_name', sa.String(length=255), nullable=False),
    sa.Column('tests_passed', sa.Integer(), nullable=False),
    sa.Column('tests_failed', sa.Integer(), nullable=False),
    sa.Column('logs', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sandbox_execution_id'], ['sandbox_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_runs_sandbox_execution_id'), ['sandbox_execution_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_runs_sandbox_execution_id'))
        batch_op.drop_index(batch_op.f('ix_test_runs_organization_id'))

    op.drop_table('test_runs')
    with op.batch_alter_table('sandbox_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sandbox_executions_sandbox_job_id'))
        batch_op.drop_index(batch_op.f('ix_sandbox_executions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_sandbox_executions_created_at'))

    op.drop_table('sandbox_executions')
    with op.batch_alter_table('mutations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mutations_trust_evaluation_id'))
        batch_op.drop_index(batch_op.f('ix_mutations_organization_id'))

    op.drop_table('mutations')
    with op.batch_alter_table('ci_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ci_statuses_pull_request_id'))
        batch_op.drop_index(batch_op.f('ix_ci_statuses_organization_id'))

    op.drop_table('ci_statuses')
    with op.batch_alter_table('trust_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trust_evaluations_trust_score'))
        batch_op.drop_index(batch_op.f('ix_trust_evaluations_patch_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_trust_evaluations_organization_id'))

    op.drop_table('trust_evaluations')
    with op.batch_alter_table('sandbox_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sandbox_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_sandbox_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_sandbox_jobs_patch_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_sandbox_jobs_organization_id'))

    op.drop_table('sandbox_jobs')
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pull_requests_project_id'))
        batch_op.drop_index(batch_op.f('ix_pull_requests_patch_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_pull_requests_organization_id'))

    op.drop_table('pull_requests')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_status'))
        batch_op.drop_index(batch_op.f('ix_decisions_patch_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_decided_by'))
        batch_op.drop_index(batch_op.f('ix_decisions_created_at'))

    op.drop_table('decisions')
    with op.batch_alter_table('patch_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patch_candidates_organization_id'))
        batch_op.drop_index(batch_op.f('ix_patch_candidates_incident_id'))
        batch_op.drop_index(batch_op.f('ix_patch_candidates_created_at'))

    op.drop_table('patch_candidates')
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_incident_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_incident_events_incident_id'))

    op.drop_table('incident_events')
    with op.batch_alter_table('fault_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fault_locations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_fault_locations_incident_id'))

    op.drop_table('fault_locations')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_project_id'))
        batch_op.drop_index(batch_op.f('ix_repositories_organization_id'))
        batch_op.drop_index(batch_op.f('ix_repositories_name'))

    op.drop_table('repositories')
    with op.batch_alter_table('project_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_policies_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_policies_organization_id'))

    op.drop_table('project_policies')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_team_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organization_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_project_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_incidents_created_at'))

    op.drop_table('incidents')
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environments_project_id'))
        batch_op.drop_index(batch_op.f('ix_environments_organization_id'))

    op.drop_table('environments')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_organization_id'))

    op.drop_table('teams')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_repository'))
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))

    op.drop_table('projects')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_organization_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
